services:
  db:
    image: postgis/postgis:15-3.3
    container_name: pasik_db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pasik_pgdata:/var/lib/postgresql/data

volumes:
  pasik_pgdata: